### ISSUE TITLE
Day 1: SeaDuke Payload

### ISSUE THREAD

**Issue by leegengyu** [mitre-attack/attack-arsenal#13]
This is the last command found in the preparation of the SeaDuke payload in `payload_configs.md`:
`pyinstaller -F python.py --upx --brute python.exe`

According to the [PyInstaller documents on using UPX,](https://pyinstaller.readthedocs.io/en/stable/usage.html#using-upx) , there does not seem to be a `--upx` option available.

Running it on the command prompt also shows that such an option was rejected in my case:
![crucial2](https://user-images.githubusercontent.com/35021368/85347241-a03fa180-b52a-11ea-83b7-aa5cc9341afe.jpg)

From my understanding, in addition to not having `--upx`, it does not seem possible to pass UPX-related options to the `pyinstaller` command, i.e. I could not pass the `--brute` option to `pyinstaller`, which would run with UPX.

The command which worked for me was `pyinstaller -F python.py --upx-exclude vcruntime140.dll`.

Without excluding `vcruntime140.dll`, the meterpreter session from `python.exe` would not be opened, as the executable would exit with an error code of -1:
![Crucial](https://user-images.githubusercontent.com/35021368/85347634-b69a2d00-b52b-11ea-8fd7-55c589973b2a.jpg)

According to a user in [an issue opened on PyInstaller's end](https://github.com/pyinstaller/pyinstaller/issues/1565), "UPX compression strips the SHA Digital Signature from vcruntime140.dll so it is no longer seen as valid."

---

1. Is there a version of `pyinstaller` that runs with the option `--upx` that I was unaware of?
2. Is there a way to pass the option of `--brute` to the UPX that is running with PyInstaller (if my version of the command is correct)?

**Comment by jcwilliamsATmitre** [comment]
hey @leegengyu!

Those are actually two separate commands that got merged somehow 🤦‍♂️

```
1. pyinstaller -F python.py
2. upx --brute python.exe
```

The 2nd is using https://github.com/upx/upx, I have sent a pull to update the instructions. Sorry about the confusion and thanks for running down all these issues!
