### ISSUE TITLE
Day 1: CALDERA .zip Payload

### ISSUE THREAD

**Issue by leegengyu** [mitre-attack/attack-arsenal#17]
Hello,

For Day 1.A of APT29 executed using the CALDERA plugin, phase 7 uses the `Modified-SysInternalsSuite.zip` payload.

This zip file consists of the following:
1. accesschk.exe
2. hostui.txt
3. javamtsup.exe
4. psversion.txt
5. readme.txt

While it is mentioned in [a section in the README](https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29/CALDERA_DIY/evals#setting-up-payloads) that the Python script "dynamically updates the payloads to the appropriate IP and port" (which it does in effect), it does not update the payloads in the said zip file to my understanding.

To this end, would like to clarify if are we required to manually update the appropriate IP and port in each of the 5 files above (where required), and zip them when done, before placing them back into the `plugins/evals/payloads` directory? This would be due to the fact that the Python script only covers `.ps1` and `.txt` files?

Thank you!

**Comment by jstroud-mitre** [comment]
> To this end, would like to clarify if are we required to manually update the appropriate IP and port in each of the 5 files above (where required), and zip them when done, before placing them back into the plugins/evals/payloads directory? This would be due to the fact that the Python script only covers .ps1 and .txt files?

@leegengyu you're absolutely correct! 
If you want to update the .exe's you'll have to re-generate them and I suggest checking out the evals steps for day-1 and day-2 [here](https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29/Emulation_Plan) for further insights in how the payloads were used so you have an idea on what you'll have to update.

**Comment by leegengyu** [comment]
Thank you for the clarification @jstroud-mitre !
