### ISSUE TITLE
getting error caldera 2.7.0

### ISSUE THREAD

**Issue by prashantvidja** [mitre-attack/attack-arsenal#20]
Hello,

it working fine for 2.6.6.
This plugin not work in 2.7.0 getting below error. 

> 2020-08-28 18:03:33 - DEBUG (data_svc.py:110 _load) ValidationError({'visible': ['Unknown field.']},)
> Traceback (most recent call last):
>   File "/home/ubuntu/caldera/app/service/data_svc.py", line 105, in _load
>     await self._load_adversaries(plug)
>   File "/home/ubuntu/caldera/app/service/data_svc.py", line 115, in _load_adversaries
>     adversary = Adversary.load(adv)
>   File "/home/ubuntu/caldera/app/utility/base_object.py", line 81, in load
>     return cls.schema.load(dict_obj)
>   File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 723, in load
>     data, many=many, partial=partial, unknown=unknown, postprocess=True
>   File "/usr/local/lib/python3.6/dist-packages/marshmallow/schema.py", line 904, in _do_load
>     raise exc
> marshmallow.exceptions.ValidationError: {'visible': ['Unknown field.']} 

Any plan to release for 2.7.0

Thanks

**Comment by jcwilliamsATmitre** [comment]
hey @prashantvidja!

Yeah our plan was to just keep this plugin at version 2.6.6.
