### ISSUE TITLE
Day 2: Step 14.B - Password Not Showing

### ISSUE THREAD

**Issue by leegengyu** [mitre-attack/attack-arsenal#9]
When I executed `wmidump` (point 6 of Step 14.B), all of the passwords which returned were `(null)`:
![image](https://user-images.githubusercontent.com/35021368/85192343-bebc5780-b2f4-11ea-851b-bb6e33544a3b.png)

Looking at `stepFourteen_credDump.ps1`, I found `$ProcessInfo.Arguments = @("privilege::debug","sekurlsa::logonpasswords","exit");` which were passed into the Mimikatz executable. I decided to run `m.exe` on the victim machine with the same 2 commands manually.

This is an example of a paragraph from the output after running the above 2 commands:
![image](https://user-images.githubusercontent.com/35021368/85192436-1955b380-b2f5-11ea-9a54-500192668eb2.png)

The white arrow in the screenshot shows that for this particular Authentication Id, that field has a value of `(null)`. Additionally, manual execution of the executable does indeed show that **all** Password fields had a value of `(null)`.

I came across this [Microsoft link](https://support.microsoft.com/en-sg/help/2871997/microsoft-security-advisory-update-to-improve-credentials-protection-a), and attempted a shot:

In `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest`, there was no `UseLogonCredential` originally:
![image](https://user-images.githubusercontent.com/35021368/85192533-6df92e80-b2f5-11ea-93ce-830541a29f03.png)

After adding in `UseLogonCredential` and setting it to `1`:
![image](https://user-images.githubusercontent.com/35021368/85192545-79e4f080-b2f5-11ea-9275-0edab2c7c5c2.png)

I manually executed the Mimikatz executable first, and found that for the same Authentication Id, I was able to see the password (under Kerberos) now.
![image](https://user-images.githubusercontent.com/35021368/85192585-a3058100-b2f5-11ea-9bf1-2f7bc652eb4c.png)

I executed `wmidump` this time, and found that the password was showing up (as expected based on the second time the manual execution was carried out):
![image](https://user-images.githubusercontent.com/35021368/85192683-055e8180-b2f6-11ea-9443-3d3dbe47bdce.png)

I am not sure if ...:
1. ... there is indeed a missing setup step (which would be under `Victim Setup`), or if there is something that I missed in the setup that caused me to see only `(null)` values as passwords.
2. ... the addition of the registry entry (as shown above) is a correct fix in this case, should there indeed be a missing setup step. Interestingly the new registry entry was under WDigest, while the expected passwords appeared in the Kerberos section of the Mimikatz executable output instead.

**Comment by jcwilliamsATmitre** [comment]
Hello again @leegengyu!

And yeah you're right, we have that as part of our environment configuration (https://attackevals.mitre.org/APT29/environment.html). Added to the `Victim Setup` as you suggested, thanks!

In regards to the section of Mimikatz output, it may depend on how you originally logged into the during setup box (which dictates how/where the credentials are cached).

**Comment by leegengyu** [comment]
I see. I had totally missed out on the bottom section of that page and focused solely on the instructions in `README.md`.

Thank you for addressing this so quickly @jcwilliamsATmitre!

**Comment by jwillyamz** [comment]
Glad to help, and thank you for pointing this out! As you said, this was something we should have included in the readme as well so great catch.
